[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
remappings = [
  "@account-abstraction/=lib/account-abstraction/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
thanos_sepolia = "https://rpc.thanos-sepolia.tokamak.network"
