[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true
libraries = [
  "poseidon-solidity/PoseidonT3.sol:PoseidonT3:0x203a488c06e9add25d4b51f7ede8e56bcc4b1a1c",
  "poseidon-solidity/PoseidonT6.sol:PoseidonT6:0x666333F371685334CdD69bdDdaFBABc87CE7c7Db",
]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "poseidon-solidity/=node_modules/poseidon-solidity/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "v4-core/=lib/v4-core/",
  "v4-periphery/=lib/v4-periphery/",
  "@uniswap/v4-core/=lib/v4-core/",
  "permit2/=lib/v4-periphery/lib/permit2/",
]

[rpc_endpoints]
ethereum_sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
ethereum_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api", chain = 11155111 }
